### ISSUE TITLE
unknown field OnCreate & OnDelete

### ISSUE THREAD

**Issue by seun-otosho** [restsend/gormpher#1]
unknown field OnCreate in struct literal of type struct{Model any; Group string; Name string; GetDB gormpher.GetDB; Pagination bool; AllowMethods int; EditFields []string; FilterFields []string; OrderFields []string; SearchFields []string; Views []gormpher.QueryView; BeforeCreate gormpher.BeforeCreateFunc; BeforeUpdate gormpher.BeforeUpdateFunc; BeforeDelete gormpher.BeforeDeleteFunc; BeforeRender gormpher.BeforeRenderFunc; modelElem reflect.Type; jsonPKName string; gormPKName string; preloads []string; jsonToFields map[string]string; jsonToKinds map[string]reflect.Kind}
./main.go:115:4: unknown field OnDelete in struct literal of type struct{Model any; Group string; Name string; GetDB gormpher.GetDB; Pagination bool; AllowMethods int; EditFields []string; FilterFields []string; OrderFields []string; SearchFields []string; Views []gormpher.QueryView; BeforeCreate gormpher.BeforeCreateFunc; BeforeUpdate gormpher.BeforeUpdateFunc; BeforeDelete gormpher.BeforeDeleteFunc; BeforeRender gormpher.BeforeRenderFunc; modelElem reflect.Type; jsonPKName string; gormPKName string; preloads []string; jsonToFields map[string]string; jsonToKinds map[string]reflect.Kind}

**Comment by szluyu99** [comment]
Sorry, I forgot to update the code in README. It has been updated, or you can directly refer to the examples directory,

**Comment by seun-otosho** [comment]
Beautiful, many thanks
Now it works!
Well done to you and the team for this great job
